### ISSUE TITLE
lib/gatein-management-api-2.1.0.Final.jar already exists. Skip or overwrite!!!

### ISSUE THREAD

**Issue by Lifestohack** [exo-addons/staging-extension#43]
[ERROR] File lib/gatein-management-api-2.1.0.Final.jar already exists.
[ERROR] File lib/gatein-management-spi-2.1.0.Final.jar already exists.
[ERROR] File lib/gatein-management-core-2.1.0.Final.jar already exists.
[ERROR] File lib/gatein-management-rest-2.1.0.Final.jar already exists.
[ERROR] Installation aborted. Use --conflict=skip or --conflict=overwrite option
Am i supposed to overwrite or skip this conflict.

**Comment by madhifallah** [comment]
On my side I've overwritten the files and that was fine.
